config/routes.rb
Rails.application.routes.draw do
  
   namespace :api, defaults: { format: :json } do
     match '/events', to: 'events#index', via: [:options]
     resources :events, only: [:create]
   end

  resources :registered_applications

  devise_for :users
  resources :users do
    resources :registered_applications
   end
  
  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

 
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
   
    before_filter :set_access_control_headers

   def set_access_control_headers
 
     headers['Access-Control-Allow-Origin'] = '*'

     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

   skip_before_action :verify_authenticity_token
 
   def create
      @registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
        
        if @registered_application
        @event = @registered_application.events.new(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render @event.errors, status: :unprocessable_entity
        end
      else
        render json: "Unregistered application", status: :unprocessable_entity
      end
   end

   private

   def event_params
     params.permit(:name)
   end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    
    
  if current_user
  @user = current_user
    
  @registered_applications = @user.registered_applications.all
else
end
  
  end

  def show
    @user = current_user
    @registered_application = @user.registered_applications.find(params[:id])
    
    @events = @registered_application.events.group_by(&:name)
  end

  def new
     @registered_application = RegisteredApplication.new
  end


  def create
      @user = current_user
      @registered_application = @user.registered_applications.build(params.require(:registered_application).permit(:name, :url))
     if @registered_application.save
       flash[:notice] = "Registered application was saved."
       redirect_to registered_applications_path
     else
       flash[:error] = "There was an error saving the registered application. Please try again."
       render :new
     end
   end

  def edit
      @user = current_user
      @registered_application = @user.registered_applications.find(params[:id])

     
  end

  def update
      @user = current_user
      @registered_application = @user.registered_applications.find(params[:id])
       if @registered_application.update_attributes(params.require(:registered_application).permit(:name, :url))
       flash[:notice] = "Registered application was saved."
       redirect_to registered_applications_path
     else
       flash[:error] = "There was an error saving the registered application. Please try again."
       render :edit
     end
  end

  def destroy
    @user = current_user
    @registered_application = @user.registered_applications.find(params[:id])

    if @registered_application.destroy
       flash[:notice] = "Registered application was saved."
       redirect_to @registered_application
     else
       flash[:error] = "There was an error saving the registered application. Please try again."
       render :index
     end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>Bloccit</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
   <ul>
     <ul class="nav nav-tabs">
       <li><%= link_to "Bloccit", welcome_index_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>
       <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
     </ul>
     <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
   <%= yield %>
   </div>

 </body>
 </html>

app/views/registered_applications/edit.html.erb
<%= form_for @registered_application do |f| %>
   <%= f.label :name%>
   <%= f.text_field :name %>
 
   <%= f.label :url %>
   <%= f.text_area :url %>
 
   <%= f.submit "Save" %>
 <% end %>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>

 <% if @current_user %>
<%= link_to "New Registered Application", new_registered_application_path(@registered_application), class: 'btn btn-success' %>
    


<% @registered_applications.each do |registered_applications| %>
  <p><%= link_to registered_applications.url, registered_applications %></p>

<% end %>
<% end %>

app/views/registered_applications/new.html.erb
<%= form_for @registered_application do |f| %>
   <%= f.label :name%>
   <%= f.text_field :name %>
 
   <%= f.label :url %>
   <%= f.text_area :url %>
 
   <%= f.submit "Save" %>
 <% end %>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>
<p><%= @registered_application.url %></p>

<p><%= pie_chart @registered_application.events.group(:name).count %></p>
<p><%= line_chart @registered_application.events.group_by_day(:created_at).count %></p>

<%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>


<% if @registered_application %>
       <%= link_to "Delete registered application", @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>  
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p>This is the home page for Bloccit.</p>